error:
  whitelabel:
    enabled: false

amazon:
  associate_id: habuma-20

logging:
  level:
    root: info

server:
  port: 9400

#spring:
#  h2:
#    console:
#      enabled: true

#spring:
#  datasource:
#        url: jdbc:mysql://10.16.10.22:3306/zoor
#        username: ibuildings
#        password: tCm#f9VpvkMm
#        driver-class-name: com.mysql.jdbc.Driver
